### Foundations: **Cleaning & Exploring the Applicant Dataset**
### Day 1: **Exploring Applicants Dataset**
The dataset contains missing values, duplicate records, inconsistent text casing, and irregular data formatting. The goal is to identify these data quality issues, investigate them, and apply appropriate cleaning techniques using Python and Pandas.

In [1]:
import pandas as pd
df = pd.read_csv(r"C:\Users\New Computer City\Week 1 Data Cleaning Project\applicants.csv")
print(df)

    Applicant Name                       Email         Phone  \
0    Ayesha Ansari                         NaN  0337 4961312
1     Hassan Malik    hassan.malik19@gmail.com  0323 5456272
2      Danish Khan     danish.khan44@gmail.com   03352156902
3      Omar Sheikh     omar.sheikh47@gmail.com   03281170307
4      BILAL IQBAL      BILAL.IQBAL2@GMAIL.COM  0325-5437923
..             ...                         ...           ...
81     Kamran Butt     kamran.butt57@gmail.com  0348 9284509
82     Hamza Iqbal     hamza.iqbal60@gmail.com  0306-9633492
83   Rabia Hussain    rabia.hussain8@gmail.com  0321 5924115
84       Hira Butt       hira.butt14@gmail.com  0301 2016911
85  Hamza Siddiqui  hamza.siddiqui67@gmail.com   03257668663

            Domain Applied             University Application Date  \
0          Web Development     Comsats University       2026-06-24
1             Data Science             Fast NUCES       27/05/2026
2       Mobile Development                COMSATS       16/08/2026
3              DataScience  University of Karachi       20-08-2026
4        graphic designing            IBA Karachi       22-02-2026
..                     ...                    ...              ...
81                  webdev             Fast NUCES       2026-06-21
82       Digital Marketing  University of Karachi       24-04-2026
83            DATA SCIENCE             Fast NUCES       18-09-2026
84  Mobile App Development                    NaN       2026-02-20
85         Web Development         NED University       25/09/2026

          Status
0       SELECTED
1   Under Review
2   UNDER REVIEW
3   UNDER REVIEW
4       rejected
..           ...
81  under review
82  UNDER REVIEW
83      SELECTED
84  UNDER REVIEW
85  UNDER REVIEW

[86 rows x 7 columns]

In [2]:
# Dataset Dimension
df.shape

(86, 7)

In [3]:
# Column names, data types and non-null values
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 86 entries, 0 to 85
Data columns (total 7 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Applicant Name    83 non-null     str
 1   Email             80 non-null     str
 2   Phone             86 non-null     str
 3   Domain Applied    86 non-null     str
 4   University        80 non-null     str
 5   Application Date  86 non-null     str
 6   Status            82 non-null     str
dtypes: str(7)
memory usage: 4.8 KB

In [4]:
# First 5 rows of the dataset
df.head()

,Applicant Name,Email,Phone,Domain Applied,University,Application Date,Status
0,Ayesha Ansari,NaN,0337 4961312,Web Development,Comsats University,2026-06-24,SELECTED
1,Hassan Malik,hassan.malik19@gmail.com,0323 5456272,Data Science,Fast NUCES,27/05/2026,Under Review
2,Danish Khan,danish.khan44@gmail.com,03352156902,Mobile Development,COMSATS,16/08/2026,UNDER REVIEW
3,Omar Sheikh,omar.sheikh47@gmail.com,03281170307,DataScience,University of Karachi,20-08-2026,UNDER REVIEW
4,BILAL IQBAL,BILAL.IQBAL2@GMAIL.COM,0325-5437923,graphic designing,IBA Karachi,22-02-2026,rejected

In [5]:
# Missing values in each column
df.isnull().sum()

Applicant Name      3
Email               6
Phone               0
Domain Applied      0
University          6
Application Date    0
Status              4
dtype: int64

In [6]:

# Duplicated rows
df.duplicated().sum()

np.int64(3)

In [7]:
# Summary statistics of the dataset
df.describe()

,Applicant Name,Email,Phone,Domain Applied,University,Application Date,Status
count,83,80,86,86,80,86,82
unique,75,77,80,18,12,73,8
top,Hassan Sheikh,BILAL.IQBAL2@GMAIL.COM,0323 5456272,Graphic Design,Fast NUCES,22-02-2026,UNDER REVIEW
freq,3,2,2,15,11,3,17

### Day 2: **Identifying and Handling Missing Values**

In [8]:
import pandas as pd
df = pd.read_csv(r"C:\Users\New Computer City\Week 1 Data Cleaning Project\applicants.csv")
cleaned_df = df.copy()
rows_before = df.shape[0]
print(df)

    Applicant Name                       Email         Phone  \
0    Ayesha Ansari                         NaN  0337 4961312
1     Hassan Malik    hassan.malik19@gmail.com  0323 5456272
2      Danish Khan     danish.khan44@gmail.com   03352156902
3      Omar Sheikh     omar.sheikh47@gmail.com   03281170307
4      BILAL IQBAL      BILAL.IQBAL2@GMAIL.COM  0325-5437923
..             ...                         ...           ...
81     Kamran Butt     kamran.butt57@gmail.com  0348 9284509
82     Hamza Iqbal     hamza.iqbal60@gmail.com  0306-9633492
83   Rabia Hussain    rabia.hussain8@gmail.com  0321 5924115
84       Hira Butt       hira.butt14@gmail.com  0301 2016911
85  Hamza Siddiqui  hamza.siddiqui67@gmail.com   03257668663

            Domain Applied             University Application Date  \
0          Web Development     Comsats University       2026-06-24
1             Data Science             Fast NUCES       27/05/2026
2       Mobile Development                COMSATS       16/08/2026
3              DataScience  University of Karachi       20-08-2026
4        graphic designing            IBA Karachi       22-02-2026
..                     ...                    ...              ...
81                  webdev             Fast NUCES       2026-06-21
82       Digital Marketing  University of Karachi       24-04-2026
83            DATA SCIENCE             Fast NUCES       18-09-2026
84  Mobile App Development                    NaN       2026-02-20
85         Web Development         NED University       25/09/2026

          Status
0       SELECTED
1   Under Review
2   UNDER REVIEW
3   UNDER REVIEW
4       rejected
..           ...
81  under review
82  UNDER REVIEW
83      SELECTED
84  UNDER REVIEW
85  UNDER REVIEW

[86 rows x 7 columns]

This dataset contains missing values that may affect data quality and the reliability of future analysis. The objective is to identify missing values across columns, understand their extent and distribution, and decide how to handle them appropriately using Python and Pandas.

In [9]:
# Remove rows with missing values in the "Email" column
cleaned_df = cleaned_df.dropna(subset=["Email"])
print(cleaned_df)

    Applicant Name                       Email         Phone  \
1     Hassan Malik    hassan.malik19@gmail.com  0323 5456272
2      Danish Khan     danish.khan44@gmail.com   03352156902
3      Omar Sheikh     omar.sheikh47@gmail.com   03281170307
4      BILAL IQBAL      BILAL.IQBAL2@GMAIL.COM  0325-5437923
6    Talha Qureshi   talha.qureshi72@gmail.com   03241368085
..             ...                         ...           ...
81     Kamran Butt     kamran.butt57@gmail.com  0348 9284509
82     Hamza Iqbal     hamza.iqbal60@gmail.com  0306-9633492
83   Rabia Hussain    rabia.hussain8@gmail.com  0321 5924115
84       Hira Butt       hira.butt14@gmail.com  0301 2016911
85  Hamza Siddiqui  hamza.siddiqui67@gmail.com   03257668663

            Domain Applied             University Application Date  \
1             Data Science             Fast NUCES       27/05/2026
2       Mobile Development                COMSATS       16/08/2026
3              DataScience  University of Karachi       20-08-2026
4        graphic designing            IBA Karachi       22-02-2026
6           Graphic Design            IBA Karachi       2026-08-22
..                     ...                    ...              ...
81                  webdev             Fast NUCES       2026-06-21
82       Digital Marketing  University of Karachi       24-04-2026
83            DATA SCIENCE             Fast NUCES       18-09-2026
84  Mobile App Development                    NaN       2026-02-20
85         Web Development         NED University       25/09/2026

          Status
1   Under Review
2   UNDER REVIEW
3   UNDER REVIEW
4       rejected
6       rejected
..           ...
81  under review
82  UNDER REVIEW
83      SELECTED
84  UNDER REVIEW
85  UNDER REVIEW

[80 rows x 7 columns]

while exploring the dataset I found 6 rows with missing emails. So I dropped 6 rows as the email is the main contact method.

In [10]:
# remove rows with missing values in the "Applicant Name" column
cleaned_df = cleaned_df.dropna(subset=["Applicant Name"])
print(cleaned_df)

    Applicant Name                       Email         Phone  \
1     Hassan Malik    hassan.malik19@gmail.com  0323 5456272
2      Danish Khan     danish.khan44@gmail.com   03352156902
3      Omar Sheikh     omar.sheikh47@gmail.com   03281170307
4      BILAL IQBAL      BILAL.IQBAL2@GMAIL.COM  0325-5437923
6    Talha Qureshi   talha.qureshi72@gmail.com   03241368085
..             ...                         ...           ...
81     Kamran Butt     kamran.butt57@gmail.com  0348 9284509
82     Hamza Iqbal     hamza.iqbal60@gmail.com  0306-9633492
83   Rabia Hussain    rabia.hussain8@gmail.com  0321 5924115
84       Hira Butt       hira.butt14@gmail.com  0301 2016911
85  Hamza Siddiqui  hamza.siddiqui67@gmail.com   03257668663

            Domain Applied             University Application Date  \
1             Data Science             Fast NUCES       27/05/2026
2       Mobile Development                COMSATS       16/08/2026
3              DataScience  University of Karachi       20-08-2026
4        graphic designing            IBA Karachi       22-02-2026
6           Graphic Design            IBA Karachi       2026-08-22
..                     ...                    ...              ...
81                  webdev             Fast NUCES       2026-06-21
82       Digital Marketing  University of Karachi       24-04-2026
83            DATA SCIENCE             Fast NUCES       18-09-2026
84  Mobile App Development                    NaN       2026-02-20
85         Web Development         NED University       25/09/2026

          Status
1   Under Review
2   UNDER REVIEW
3   UNDER REVIEW
4       rejected
6       rejected
..           ...
81  under review
82  UNDER REVIEW
83      SELECTED
84  UNDER REVIEW
85  UNDER REVIEW

[77 rows x 7 columns]

I found 3 rows with missing values in the "Applicant Name" column so i dropped 3 rows as the name as well as the email are the main contact method.

In [11]:
# filling missing values in the "University" column with "Not Specified"
cleaned_df["University"] = cleaned_df["University"].fillna("Not Specified")
print(cleaned_df)

    Applicant Name                       Email         Phone  \
1     Hassan Malik    hassan.malik19@gmail.com  0323 5456272
2      Danish Khan     danish.khan44@gmail.com   03352156902
3      Omar Sheikh     omar.sheikh47@gmail.com   03281170307
4      BILAL IQBAL      BILAL.IQBAL2@GMAIL.COM  0325-5437923
6    Talha Qureshi   talha.qureshi72@gmail.com   03241368085
..             ...                         ...           ...
81     Kamran Butt     kamran.butt57@gmail.com  0348 9284509
82     Hamza Iqbal     hamza.iqbal60@gmail.com  0306-9633492
83   Rabia Hussain    rabia.hussain8@gmail.com  0321 5924115
84       Hira Butt       hira.butt14@gmail.com  0301 2016911
85  Hamza Siddiqui  hamza.siddiqui67@gmail.com   03257668663

            Domain Applied             University Application Date  \
1             Data Science             Fast NUCES       27/05/2026
2       Mobile Development                COMSATS       16/08/2026
3              DataScience  University of Karachi       20-08-2026
4        graphic designing            IBA Karachi       22-02-2026
6           Graphic Design            IBA Karachi       2026-08-22
..                     ...                    ...              ...
81                  webdev             Fast NUCES       2026-06-21
82       Digital Marketing  University of Karachi       24-04-2026
83            DATA SCIENCE             Fast NUCES       18-09-2026
84  Mobile App Development          Not Specified       2026-02-20
85         Web Development         NED University       25/09/2026

          Status
1   Under Review
2   UNDER REVIEW
3   UNDER REVIEW
4       rejected
6       rejected
..           ...
81  under review
82  UNDER REVIEW
83      SELECTED
84  UNDER REVIEW
85  UNDER REVIEW

[77 rows x 7 columns]

FIlled out the row with missing "University" column with "Not Specified" as university is not the necessery/must element so i kept them to avoid losing useful information.

In [12]:
# filling out the missing values in the "Status" column with "Under Review"
cleaned_df["Status"] = cleaned_df["Status"].fillna("Under Review")
print(cleaned_df)

    Applicant Name                       Email         Phone  \
1     Hassan Malik    hassan.malik19@gmail.com  0323 5456272
2      Danish Khan     danish.khan44@gmail.com   03352156902
3      Omar Sheikh     omar.sheikh47@gmail.com   03281170307
4      BILAL IQBAL      BILAL.IQBAL2@GMAIL.COM  0325-5437923
6    Talha Qureshi   talha.qureshi72@gmail.com   03241368085
..             ...                         ...           ...
81     Kamran Butt     kamran.butt57@gmail.com  0348 9284509
82     Hamza Iqbal     hamza.iqbal60@gmail.com  0306-9633492
83   Rabia Hussain    rabia.hussain8@gmail.com  0321 5924115
84       Hira Butt       hira.butt14@gmail.com  0301 2016911
85  Hamza Siddiqui  hamza.siddiqui67@gmail.com   03257668663

            Domain Applied             University Application Date  \
1             Data Science             Fast NUCES       27/05/2026
2       Mobile Development                COMSATS       16/08/2026
3              DataScience  University of Karachi       20-08-2026
4        graphic designing            IBA Karachi       22-02-2026
6           Graphic Design            IBA Karachi       2026-08-22
..                     ...                    ...              ...
81                  webdev             Fast NUCES       2026-06-21
82       Digital Marketing  University of Karachi       24-04-2026
83            DATA SCIENCE             Fast NUCES       18-09-2026
84  Mobile App Development          Not Specified       2026-02-20
85         Web Development         NED University       25/09/2026

          Status
1   Under Review
2   UNDER REVIEW
3   UNDER REVIEW
4       rejected
6       rejected
..           ...
81  under review
82  UNDER REVIEW
83      SELECTED
84  UNDER REVIEW
85  UNDER REVIEW

[77 rows x 7 columns]

Filled with "Under Review". A blank status most likely means
the application hasn't been processed yet.

In [13]:
print("Rows Removed:", rows_before - cleaned_df.shape[0])
cleaned_df.isnull().sum()

Rows Removed: 9

Applicant Name      0
Email               0
Phone               0
Domain Applied      0
University          0
Application Date    0
Status              0
dtype: int64

**Result:** The dataset went from 86 rows to 77 (9 rows removed). No missing values remain.

### Day 3: **Remove Duplicate Applicants:**
There are 2 kinds of duplicates:
1- Exact Duplicates: Every column is identical so drop_duplicates() catches them.
2- Near Duplicates: The same person with slight different formatting means ali@mail.com and ALI@GMAIL.COM. plain drop_duplicates() catches them.

In [14]:
# Check exact duplicates first
print(cleaned_df.duplicated().sum())
# Remove exact duplicate rows
cleaned_df = cleaned_df.drop_duplicates()
print(cleaned_df)

3
    Applicant Name                       Email         Phone  \
1     Hassan Malik    hassan.malik19@gmail.com  0323 5456272
2      Danish Khan     danish.khan44@gmail.com   03352156902
3      Omar Sheikh     omar.sheikh47@gmail.com   03281170307
4      BILAL IQBAL      BILAL.IQBAL2@GMAIL.COM  0325-5437923
6    Talha Qureshi   talha.qureshi72@gmail.com   03241368085
..             ...                         ...           ...
81     Kamran Butt     kamran.butt57@gmail.com  0348 9284509
82     Hamza Iqbal     hamza.iqbal60@gmail.com  0306-9633492
83   Rabia Hussain    rabia.hussain8@gmail.com  0321 5924115
84       Hira Butt       hira.butt14@gmail.com  0301 2016911
85  Hamza Siddiqui  hamza.siddiqui67@gmail.com   03257668663

            Domain Applied             University Application Date  \
1             Data Science             Fast NUCES       27/05/2026
2       Mobile Development                COMSATS       16/08/2026
3              DataScience  University of Karachi       20-08-2026
4        graphic designing            IBA Karachi       22-02-2026
6           Graphic Design            IBA Karachi       2026-08-22
..                     ...                    ...              ...
81                  webdev             Fast NUCES       2026-06-21
82       Digital Marketing  University of Karachi       24-04-2026
83            DATA SCIENCE             Fast NUCES       18-09-2026
84  Mobile App Development          Not Specified       2026-02-20
85         Web Development         NED University       25/09/2026

          Status
1   Under Review
2   UNDER REVIEW
3   UNDER REVIEW
4       rejected
6       rejected
..           ...
81  under review
82  UNDER REVIEW
83      SELECTED
84  UNDER REVIEW
85  UNDER REVIEW

[74 rows x 7 columns]

Found and Removed 3 exact duplicate rows containing same information.

In [15]:
print(cleaned_df["Email"].duplicated().sum())

0

In [16]:
cleaned_df["Email"] = cleaned_df["Email"].str.strip().str.lower()
print(cleaned_df)
cleaned_df.duplicated().sum()

    Applicant Name                       Email         Phone  \
1     Hassan Malik    hassan.malik19@gmail.com  0323 5456272
2      Danish Khan     danish.khan44@gmail.com   03352156902
3      Omar Sheikh     omar.sheikh47@gmail.com   03281170307
4      BILAL IQBAL      bilal.iqbal2@gmail.com  0325-5437923
6    Talha Qureshi   talha.qureshi72@gmail.com   03241368085
..             ...                         ...           ...
81     Kamran Butt     kamran.butt57@gmail.com  0348 9284509
82     Hamza Iqbal     hamza.iqbal60@gmail.com  0306-9633492
83   Rabia Hussain    rabia.hussain8@gmail.com  0321 5924115
84       Hira Butt       hira.butt14@gmail.com  0301 2016911
85  Hamza Siddiqui  hamza.siddiqui67@gmail.com   03257668663

            Domain Applied             University Application Date  \
1             Data Science             Fast NUCES       27/05/2026
2       Mobile Development                COMSATS       16/08/2026
3              DataScience  University of Karachi       20-08-2026
4        graphic designing            IBA Karachi       22-02-2026
6           Graphic Design            IBA Karachi       2026-08-22
..                     ...                    ...              ...
81                  webdev             Fast NUCES       2026-06-21
82       Digital Marketing  University of Karachi       24-04-2026
83            DATA SCIENCE             Fast NUCES       18-09-2026
84  Mobile App Development          Not Specified       2026-02-20
85         Web Development         NED University       25/09/2026

          Status
1   Under Review
2   UNDER REVIEW
3   UNDER REVIEW
4       rejected
6       rejected
..           ...
81  under review
82  UNDER REVIEW
83      SELECTED
84  UNDER REVIEW
85  UNDER REVIEW

[74 rows x 7 columns]

np.int64(0)

In [17]:
cleaned_df[cleaned_df['Email'].duplicated(keep=False)].sort_values('Email')

,Applicant Name,Email,Phone,Domain Applied,University,Application Date,Status
52,HAMZA KHAN,hamza.khan7@gmail.com,03128082668,Web development,FAST-NUCES,2026-09-30,Selected
68,Hamza Khan,hamza.khan7@gmail.com,03128082668,Web development,FAST-NUCES,21-08-2026,Selected
1,Hassan Malik,hassan.malik19@gmail.com,0323 5456272,Data Science,Fast NUCES,27/05/2026,Under Review
31,HASSAN MALIK,hassan.malik19@gmail.com,0323 5456272,Data Science,Fast NUCES,2026-09-30,Under Review
8,KAMRAN BUTT,kamran.butt57@gmail.com,0348 9284509,webdev,Fast NUCES,2026-09-30,under review
81,Kamran Butt,kamran.butt57@gmail.com,0348 9284509,webdev,Fast NUCES,2026-06-21,under review

In [18]:
cleaned_df = cleaned_df.drop_duplicates(subset=["Email"], keep="first")
print(cleaned_df)

    Applicant Name                       Email         Phone  \
1     Hassan Malik    hassan.malik19@gmail.com  0323 5456272
2      Danish Khan     danish.khan44@gmail.com   03352156902
3      Omar Sheikh     omar.sheikh47@gmail.com   03281170307
4      BILAL IQBAL      bilal.iqbal2@gmail.com  0325-5437923
6    Talha Qureshi   talha.qureshi72@gmail.com   03241368085
..             ...                         ...           ...
80     Ahmed Malik     ahmed.malik46@gmail.com  0349 7358385
82     Hamza Iqbal     hamza.iqbal60@gmail.com  0306-9633492
83   Rabia Hussain    rabia.hussain8@gmail.com  0321 5924115
84       Hira Butt       hira.butt14@gmail.com  0301 2016911
85  Hamza Siddiqui  hamza.siddiqui67@gmail.com   03257668663

            Domain Applied             University Application Date  \
1             Data Science             Fast NUCES       27/05/2026
2       Mobile Development                COMSATS       16/08/2026
3              DataScience  University of Karachi       20-08-2026
4        graphic designing            IBA Karachi       22-02-2026
6           Graphic Design            IBA Karachi       2026-08-22
..                     ...                    ...              ...
80                 WEB DEV                COMSATS       2026-03-28
82       Digital Marketing  University of Karachi       24-04-2026
83            DATA SCIENCE             Fast NUCES       18-09-2026
84  Mobile App Development          Not Specified       2026-02-20
85         Web Development         NED University       25/09/2026

          Status
1   Under Review
2   UNDER REVIEW
3   UNDER REVIEW
4       rejected
6       rejected
..           ...
80      SELECTED
82  UNDER REVIEW
83      SELECTED
84  UNDER REVIEW
85  UNDER REVIEW

[71 rows x 7 columns]

Found and Dropped 3 near duplicate rows.

In [19]:
print(cleaned_df.duplicated().sum())
print(cleaned_df['Email'].duplicated().sum())

0
0

**Result:** The dataset went from 77 rows to 71 rows. No duplicated values remain.

### Day 4: **Standardize Text Fields**

The dataset contains inconsistent capitalization, spelling variations, and spacing in text fields. The goal is to standardize these values to improve data consistency and reliability.

**Steps:**
1. Inspect unique values in categorical columns.
2. Remove leading and trailing spaces.
3. Standardize capitalization.
4. Correct inconsistent spelling and equivalent category names.
5. Verify the cleaned values and compare them with the original data.

**Objective:** Ensure consistent text values for accurate analysis and reporting.

**Standardize Domain Applied:**

In [20]:
cleaned_df["Domain Applied"].unique()

<StringArray>
[          'Data Science',     'Mobile Development',            'DataScience',
      'graphic designing',         'Graphic Design',                 'webdev',
        'Web Development',      'digital marketing',           'DATA SCIENCE',
      'Digital Marketing',         'MOBILE APP DEV', 'Mobile App Development',
           'Digital Mktg',         'mobile app dev',        'Web development',
         'GRAPHIC DESIGN',                'WEB DEV']
Length: 17, dtype: str

In [21]:
cleaned_df["Domain Applied"] = cleaned_df["Domain Applied"].str.strip().str.lower()
# print(cleaned_df)
cleaned_df["Domain Applied"].unique()

<StringArray>
[          'data science',     'mobile development',            'datascience',
      'graphic designing',         'graphic design',                 'webdev',
        'web development',      'digital marketing',         'mobile app dev',
 'mobile app development',           'digital mktg',                'web dev']
Length: 12, dtype: str

In [22]:
domain_mapping = {"data science": "Data Science",
                  "datascience": "Data Science",
                  "graphic designing": "Graphic Design",
                  "graphic design": "Graphic Design",
                  "web development": "Web Development",
                  "webdev": "Web Development",
                  "web dev": "Web Development",
                  "mobile app development": "Mobile App Development",
                  "mobile development": "Mobile App Development",
                  "mobile app dev": "Mobile App Development",
                  "digital marketing": "Digital Marketing",
                  "digital mktg": "Digital Marketing"
                }

cleaned_df["Domain Applied"] = cleaned_df["Domain Applied"].map(domain_mapping)
print(cleaned_df["Domain Applied"].isnull().sum())   # should be 0
cleaned_df["Domain Applied"].unique()

0

<StringArray>
[          'Data Science', 'Mobile App Development',         'Graphic Design',
        'Web Development',      'Digital Marketing']
Length: 5, dtype: str

In [23]:
print(cleaned_df)

    Applicant Name                       Email         Phone  \
1     Hassan Malik    hassan.malik19@gmail.com  0323 5456272
2      Danish Khan     danish.khan44@gmail.com   03352156902
3      Omar Sheikh     omar.sheikh47@gmail.com   03281170307
4      BILAL IQBAL      bilal.iqbal2@gmail.com  0325-5437923
6    Talha Qureshi   talha.qureshi72@gmail.com   03241368085
..             ...                         ...           ...
80     Ahmed Malik     ahmed.malik46@gmail.com  0349 7358385
82     Hamza Iqbal     hamza.iqbal60@gmail.com  0306-9633492
83   Rabia Hussain    rabia.hussain8@gmail.com  0321 5924115
84       Hira Butt       hira.butt14@gmail.com  0301 2016911
85  Hamza Siddiqui  hamza.siddiqui67@gmail.com   03257668663

            Domain Applied             University Application Date  \
1             Data Science             Fast NUCES       27/05/2026
2   Mobile App Development                COMSATS       16/08/2026
3             Data Science  University of Karachi       20-08-2026
4           Graphic Design            IBA Karachi       22-02-2026
6           Graphic Design            IBA Karachi       2026-08-22
..                     ...                    ...              ...
80         Web Development                COMSATS       2026-03-28
82       Digital Marketing  University of Karachi       24-04-2026
83            Data Science             Fast NUCES       18-09-2026
84  Mobile App Development          Not Specified       2026-02-20
85         Web Development         NED University       25/09/2026

          Status
1   Under Review
2   UNDER REVIEW
3   UNDER REVIEW
4       rejected
6       rejected
..           ...
80      SELECTED
82  UNDER REVIEW
83      SELECTED
84  UNDER REVIEW
85  UNDER REVIEW

[71 rows x 7 columns]

**Domain Applied:** The column had 12+ spelling and casing variations for only
5 real domains (e.g. "web dev", "WEB DEV", "webdev"). I stripped whitespace and
lowercased the values, then mapped every variation to one of 5 standard labels
using a dictionary. After mapping, `.isnull().sum()` is 0 and `.unique()` shows
exactly 5 values, so no variation was missed.

**Standardize Status:**

In [24]:
cleaned_df["Status"] = cleaned_df["Status"].str.strip().str.title()
cleaned_df["Status"].unique()

<StringArray>
['Under Review', 'Rejected', 'Selected']
Length: 3, dtype: str

In [25]:
print(cleaned_df)

    Applicant Name                       Email         Phone  \
1     Hassan Malik    hassan.malik19@gmail.com  0323 5456272
2      Danish Khan     danish.khan44@gmail.com   03352156902
3      Omar Sheikh     omar.sheikh47@gmail.com   03281170307
4      BILAL IQBAL      bilal.iqbal2@gmail.com  0325-5437923
6    Talha Qureshi   talha.qureshi72@gmail.com   03241368085
..             ...                         ...           ...
80     Ahmed Malik     ahmed.malik46@gmail.com  0349 7358385
82     Hamza Iqbal     hamza.iqbal60@gmail.com  0306-9633492
83   Rabia Hussain    rabia.hussain8@gmail.com  0321 5924115
84       Hira Butt       hira.butt14@gmail.com  0301 2016911
85  Hamza Siddiqui  hamza.siddiqui67@gmail.com   03257668663

            Domain Applied             University Application Date  \
1             Data Science             Fast NUCES       27/05/2026
2   Mobile App Development                COMSATS       16/08/2026
3             Data Science  University of Karachi       20-08-2026
4           Graphic Design            IBA Karachi       22-02-2026
6           Graphic Design            IBA Karachi       2026-08-22
..                     ...                    ...              ...
80         Web Development                COMSATS       2026-03-28
82       Digital Marketing  University of Karachi       24-04-2026
83            Data Science             Fast NUCES       18-09-2026
84  Mobile App Development          Not Specified       2026-02-20
85         Web Development         NED University       25/09/2026

          Status
1   Under Review
2   Under Review
3   Under Review
4       Rejected
6       Rejected
..           ...
80      Selected
82  Under Review
83      Selected
84  Under Review
85  Under Review

[71 rows x 7 columns]

**Status:** standardized with `.str.strip().str.title()` into 3 values
(Under Review, Selected, Rejected).

**Standardize Applicant Name:**

In [26]:
cleaned_df["Applicant Name"] = cleaned_df["Applicant Name"].str.strip().str.title()
print(cleaned_df)

    Applicant Name                       Email         Phone  \
1     Hassan Malik    hassan.malik19@gmail.com  0323 5456272
2      Danish Khan     danish.khan44@gmail.com   03352156902
3      Omar Sheikh     omar.sheikh47@gmail.com   03281170307
4      Bilal Iqbal      bilal.iqbal2@gmail.com  0325-5437923
6    Talha Qureshi   talha.qureshi72@gmail.com   03241368085
..             ...                         ...           ...
80     Ahmed Malik     ahmed.malik46@gmail.com  0349 7358385
82     Hamza Iqbal     hamza.iqbal60@gmail.com  0306-9633492
83   Rabia Hussain    rabia.hussain8@gmail.com  0321 5924115
84       Hira Butt       hira.butt14@gmail.com  0301 2016911
85  Hamza Siddiqui  hamza.siddiqui67@gmail.com   03257668663

            Domain Applied             University Application Date  \
1             Data Science             Fast NUCES       27/05/2026
2   Mobile App Development                COMSATS       16/08/2026
3             Data Science  University of Karachi       20-08-2026
4           Graphic Design            IBA Karachi       22-02-2026
6           Graphic Design            IBA Karachi       2026-08-22
..                     ...                    ...              ...
80         Web Development                COMSATS       2026-03-28
82       Digital Marketing  University of Karachi       24-04-2026
83            Data Science             Fast NUCES       18-09-2026
84  Mobile App Development          Not Specified       2026-02-20
85         Web Development         NED University       25/09/2026

          Status
1   Under Review
2   Under Review
3   Under Review
4       Rejected
6       Rejected
..           ...
80      Selected
82  Under Review
83      Selected
84  Under Review
85  Under Review

[71 rows x 7 columns]

**Applicant Name:** stripped extra spaces and converted to Title Case.

**Standardize University Names:**

In [27]:
cleaned_df["University"] = cleaned_df["University"].str.strip().str.lower()
cleaned_df["University"].unique()

<StringArray>
[           'fast nuces',               'comsats', 'university of karachi',
           'iba karachi',        'ned university',                  'nust',
                   'ned',                  'lums',    'comsats university',
               'n.u.s.t',         'not specified',            'fast-nuces',
                   'uok']
Length: 13, dtype: str

In [28]:
university_mapping = {"fast nuces": "FAST NUCES",
                      "fast-nuces": "FAST NUCES",
                      "iba karachi": "IBA Karachi",
                      "ned": "NED University",
                      "ned university": "NED University",
                      "nust": "NUST",
                      "n.u.s.t": "NUST",
                      "uok": "University of Karachi",
                      "university of karachi": "University of Karachi",
                      "comsats": "COMSATS University",
                      "comsats university": "COMSATS University",
                      "lums": "LUMS",
                      "not specified": "Not Specified"
                      }

cleaned_df["University"] = cleaned_df["University"].map(university_mapping)
print(cleaned_df["University"].isnull().sum())   # should be 0

0

In [29]:
print(cleaned_df)

    Applicant Name                       Email         Phone  \
1     Hassan Malik    hassan.malik19@gmail.com  0323 5456272
2      Danish Khan     danish.khan44@gmail.com   03352156902
3      Omar Sheikh     omar.sheikh47@gmail.com   03281170307
4      Bilal Iqbal      bilal.iqbal2@gmail.com  0325-5437923
6    Talha Qureshi   talha.qureshi72@gmail.com   03241368085
..             ...                         ...           ...
80     Ahmed Malik     ahmed.malik46@gmail.com  0349 7358385
82     Hamza Iqbal     hamza.iqbal60@gmail.com  0306-9633492
83   Rabia Hussain    rabia.hussain8@gmail.com  0321 5924115
84       Hira Butt       hira.butt14@gmail.com  0301 2016911
85  Hamza Siddiqui  hamza.siddiqui67@gmail.com   03257668663

            Domain Applied             University Application Date  \
1             Data Science             FAST NUCES       27/05/2026
2   Mobile App Development     COMSATS University       16/08/2026
3             Data Science  University of Karachi       20-08-2026
4           Graphic Design            IBA Karachi       22-02-2026
6           Graphic Design            IBA Karachi       2026-08-22
..                     ...                    ...              ...
80         Web Development     COMSATS University       2026-03-28
82       Digital Marketing  University of Karachi       24-04-2026
83            Data Science             FAST NUCES       18-09-2026
84  Mobile App Development          Not Specified       2026-02-20
85         Web Development         NED University       25/09/2026

          Status
1   Under Review
2   Under Review
3   Under Review
4       Rejected
6       Rejected
..           ...
80      Selected
82  Under Review
83      Selected
84  Under Review
85  Under Review

[71 rows x 7 columns]

**University:** mapped university to get the exact university names.

**Result:**
Domain Applied went from 18 spelling/casing variations to exactly
5 standard domains (0 missing after mapping). Status now has 3 consistent
values (Under Review, Selected, Rejected), and Applicant Name is in consistent
Title Case. No rows were removed in this step: the dataset is still 71 rows x 7 columns.

### Day 5: **Fix Data Types (Especially Dates and Phone Numbers)**

**The problem:** A date or phone number that's stored as plain text looks right to a human but can't
be sorted, filtered, or calculated on correctly by code until it's converted to the proper type.

**Step 1: Phone numbers**

In [30]:
cleaned_df["Phone"] = cleaned_df["Phone"].str.replace(" ", "", regex=False).str.replace("-", "", regex=False)
print(cleaned_df)

    Applicant Name                       Email        Phone  \
1     Hassan Malik    hassan.malik19@gmail.com  03235456272
2      Danish Khan     danish.khan44@gmail.com  03352156902
3      Omar Sheikh     omar.sheikh47@gmail.com  03281170307
4      Bilal Iqbal      bilal.iqbal2@gmail.com  03255437923
6    Talha Qureshi   talha.qureshi72@gmail.com  03241368085
..             ...                         ...          ...
80     Ahmed Malik     ahmed.malik46@gmail.com  03497358385
82     Hamza Iqbal     hamza.iqbal60@gmail.com  03069633492
83   Rabia Hussain    rabia.hussain8@gmail.com  03215924115
84       Hira Butt       hira.butt14@gmail.com  03012016911
85  Hamza Siddiqui  hamza.siddiqui67@gmail.com  03257668663

            Domain Applied             University Application Date  \
1             Data Science             FAST NUCES       27/05/2026
2   Mobile App Development     COMSATS University       16/08/2026
3             Data Science  University of Karachi       20-08-2026
4           Graphic Design            IBA Karachi       22-02-2026
6           Graphic Design            IBA Karachi       2026-08-22
..                     ...                    ...              ...
80         Web Development     COMSATS University       2026-03-28
82       Digital Marketing  University of Karachi       24-04-2026
83            Data Science             FAST NUCES       18-09-2026
84  Mobile App Development          Not Specified       2026-02-20
85         Web Development         NED University       25/09/2026

          Status
1   Under Review
2   Under Review
3   Under Review
4       Rejected
6       Rejected
..           ...
80      Selected
82  Under Review
83      Selected
84  Under Review
85  Under Review

[71 rows x 7 columns]

In [31]:
print(cleaned_df["Phone"].str.len().value_counts())

Phone
11    71
Name: count, dtype: int64

**Phone:**
Kept as text (phone numbers are identifiers, and leading zeros must
be preserved). Removed dashes and spaces with `.str.replace()`. All 71 numbers
are now 11 digits starting with 03. I did not add country codes because the
data is all local Pakistani numbers and the task needs consistent formatting only.

**Step 2: Dates**

In [32]:
# 1. Back up the original text, BEFORE converting
raw_dates = cleaned_df["Application Date"].copy()

In [33]:
# 2. Missing dates before conversion
print(cleaned_df["Application Date"].isnull().sum())

0

In [34]:
# 3. Convert text to real dates (unreadable values become NaT)
cleaned_df["Application Date"] = pd.to_datetime(cleaned_df["Application Date"], errors = "coerce", format = "mixed", dayfirst = True)
print(cleaned_df)

    Applicant Name                       Email        Phone  \
1     Hassan Malik    hassan.malik19@gmail.com  03235456272
2      Danish Khan     danish.khan44@gmail.com  03352156902
3      Omar Sheikh     omar.sheikh47@gmail.com  03281170307
4      Bilal Iqbal      bilal.iqbal2@gmail.com  03255437923
6    Talha Qureshi   talha.qureshi72@gmail.com  03241368085
..             ...                         ...          ...
80     Ahmed Malik     ahmed.malik46@gmail.com  03497358385
82     Hamza Iqbal     hamza.iqbal60@gmail.com  03069633492
83   Rabia Hussain    rabia.hussain8@gmail.com  03215924115
84       Hira Butt       hira.butt14@gmail.com  03012016911
85  Hamza Siddiqui  hamza.siddiqui67@gmail.com  03257668663

            Domain Applied             University Application Date  \
1             Data Science             FAST NUCES       2026-05-27
2   Mobile App Development     COMSATS University       2026-08-16
3             Data Science  University of Karachi       2026-08-20
4           Graphic Design            IBA Karachi       2026-02-22
6           Graphic Design            IBA Karachi       2026-08-22
..                     ...                    ...              ...
80         Web Development     COMSATS University       2026-03-28
82       Digital Marketing  University of Karachi       2026-04-24
83            Data Science             FAST NUCES       2026-09-18
84  Mobile App Development          Not Specified       2026-02-20
85         Web Development         NED University       2026-09-25

          Status
1   Under Review
2   Under Review
3   Under Review
4       Rejected
6       Rejected
..           ...
80      Selected
82  Under Review
83      Selected
84  Under Review
85  Under Review

[71 rows x 7 columns]

In [35]:
# 4. Missing dates after conversion
print(cleaned_df["Application Date"].isnull().sum())

2

In [36]:
# 5. See which rows they are and what was originally written
cleaned_df[cleaned_df["Application Date"].isnull()].assign(original=raw_dates)

,Applicant Name,Email,Phone,Domain Applied,University,Application Date,Status,original
9,Hira Malik,hira.malik41@gmail.com,03005148725,Web Development,NED University,NaT,Selected,not sure
78,Usman Malik,usman.malik75@gmail.com,03387136687,Graphic Design,NED University,NaT,Selected,not sure

In [37]:
# 6. Confirm the type and the row count
cleaned_df.info()                                          
print(cleaned_df.shape)

<class 'pandas.DataFrame'>
Index: 71 entries, 1 to 85
Data columns (total 7 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Applicant Name    71 non-null     str
 1   Email             71 non-null     str
 2   Phone             71 non-null     str
 3   Domain Applied    71 non-null     str
 4   University        71 non-null     str
 5   Application Date  69 non-null     datetime64[us]
 6   Status            71 non-null     str
dtypes: datetime64[us](1), str(6)
memory usage: 6.5 KB
(71, 7)

**Application Date**

The column held three text formats (2026-08-22, 27/05/2026, 20-08-2026). I
converted it with `pd.to_datetime(errors="coerce", format="mixed",
dayfirst=True)` and confirmed with `df.info()` that it is now datetime64.

2 values ("not sure") couldn't be parsed and became NaT. I kept these rows and
left the date as missing instead of inventing one, because the rest of each
row is valid and the date isn't critical for outreach. Row count is still 71.

### Day 6: **Data Quality Summary**

**Starting dataset:** 86 rows, 7 columns

**Issues found:**
- Missing values: 3 in Applicant Name, 6 in Email, 6 in University, 4 in Status
- 3 exact duplicate rows, plus 3 more duplicate applications found by
  matching Email (same email in different casing)
- Domain Applied had 18 spelling/casing variations for only 5 real domains
- Status had 8 variations for 3 real values
- Applicant Name and Email had inconsistent casing and extra spaces
- Application Date was stored as text in three formats, including 2 unreadable
  values ("not sure")
- Phone numbers contained inconsistent dash/space formatting

**Actions taken:**
- Dropped 3 rows with missing Applicant Name (unusable without identification)
- Dropped 6 rows with missing Email (the contact method and the key for
  detecting duplicates)
- Filled missing University with "Not Specified" (non-critical field)
- Filled missing Status with "Under Review" (default for unprocessed applications)
- Removed 6 duplicate rows total (3 exact, 3 by matching Email)
- Standardized Domain Applied into 5 categories using a mapping dictionary
- Standardized Status into 3 values, and Names to Title Case
- Converted Application Date to datetime64; the 2 unreadable values became
  NaT and were kept, since the rest of those rows is valid
- Removed dashes and spaces from Phone (kept as text to preserve leading zeros)

**Final dataset:** 71 rows, 7 columns (15 rows removed in total), no missing
values in critical fields (name, email), no duplicates, consistent formatting.
Only Application Date has 2 missing values.

### Day 7: **Exporting csv:**

In [38]:
cleaned_df.to_csv("applicants_cleaned.csv", index = False, date_format = "%d-%m-%Y")

In [39]:
check = pd.read_csv("applicants_cleaned.csv")
print(check.shape)
check.head()

(71, 7)

,Applicant Name,Email,Phone,Domain Applied,University,Application Date,Status
0,Hassan Malik,hassan.malik19@gmail.com,3235456272,Data Science,FAST NUCES,27-05-2026,Under Review
1,Danish Khan,danish.khan44@gmail.com,3352156902,Mobile App Development,COMSATS University,16-08-2026,Under Review
2,Omar Sheikh,omar.sheikh47@gmail.com,3281170307,Data Science,University of Karachi,20-08-2026,Under Review
3,Bilal Iqbal,bilal.iqbal2@gmail.com,3255437923,Graphic Design,IBA Karachi,22-02-2026,Rejected
4,Talha Qureshi,talha.qureshi72@gmail.com,3241368085,Graphic Design,IBA Karachi,22-08-2026,Rejected